pipeline:
  deployment:
    image: appleboy/drone-ssh
    host: nibble.online.ntnu.no
    user: nibble
    username: nibble 
    port: 22030
    key: ${SSH_KEY}
    when:
      event: push
      branch: master
    script:
      - git checkout master
      - git pull origin master
