pipeline:
  deployment:
    image: appleboy/drone-ssh
    host: nibble.online.ntnu.no
    username: nibble
    port: 22030
    key: ${NIBBLE_DEPLOY_KEY}
    when:
      event: push
      branch: master
    script:
      - cd /home/nibble
      - echo deployed > test-nibble.txt
