pipeline:
  deployment:
    image: appleboy/drone-ssh
    host: nibble.online.ntnu.no
    username: nibble
    port: 22030
    key: ${DEPLOY_KEY}
    when:
      event: push
      branch: master
    script:
      - cd /home/nibble/Nibble2
      - ls
      - git checkout master
      - git pull origin master
